#KNN

#Exploring the dataset

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization

In [2]:
df = pd.read_csv("water_potability.csv")
df.head()

ph    Hardness        Solids  Chloramines     Sulfate  Conductivity  \
0       NaN  204.890455  20791.318981     7.300212  368.516441    564.308654   
1  3.716080  129.422921  18630.057858     6.635246         NaN    592.885359   
2  8.099124  224.236259  19909.541732     9.275884         NaN    418.606213   
3  8.316766  214.373394  22018.417441     8.059332  356.886136    363.266516   
4  9.092223  181.101509  17978.986339     6.546600  310.135738    398.410813   

   Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       10.379783        86.990970   2.963135           0  
1       15.180013        56.329076   4.500656           0  
2       16.868637        66.420093   3.055934           0  
3       18.436524       100.341674   4.628771           0  
4       11.558279        31.997993   4.075075           0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   ph               2785 non-null   float64
 1   Hardness         3276 non-null   float64
 2   Solids           3276 non-null   float64
 3   Chloramines      3276 non-null   float64
 4   Sulfate          2495 non-null   float64
 5   Conductivity     3276 non-null   float64
 6   Organic_carbon   3276 non-null   float64
 7   Trihalomethanes  3114 non-null   float64
 8   Turbidity        3276 non-null   float64
 9   Potability       3276 non-null   int64  
dtypes: float64(9), int64(1)
memory usage: 256.1 KB


In [4]:
df = df.dropna().reset_index(drop=True)
df

ph    Hardness        Solids  Chloramines     Sulfate  \
0      8.316766  214.373394  22018.417441     8.059332  356.886136   
1      9.092223  181.101509  17978.986339     6.546600  310.135738   
2      5.584087  188.313324  28748.687739     7.544869  326.678363   
3     10.223862  248.071735  28749.716544     7.513408  393.663396   
4      8.635849  203.361523  13672.091764     4.563009  303.309771   
...         ...         ...           ...          ...         ...   
2006   8.989900  215.047358  15921.412018     6.297312  312.931022   
2007   6.702547  207.321086  17246.920347     7.708117  304.510230   
2008  11.491011   94.812545  37188.826022     9.263166  258.930600   
2009   6.069616  186.659040  26138.780191     7.747547  345.700257   
2010   4.668102  193.681735  47580.991603     7.166639  359.948574   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
0       363.266516       18.436524       100.341674   4.628771           0  
1       398.410813       11.558279        31.997993   4.075075           0  
2       280.467916        8.399735        54.917862   2.559708           0  
3       283.651634       13.789695        84.603556   2.672989           0  
4       474.607645       12.363817        62.798309   4.401425           0  
...            ...             ...              ...        ...         ...  
2006    390.410231        9.899115        55.069304   4.613843           1  
2007    329.266002       16.217303        28.878601   3.442983           1  
2008    439.893618       16.172755        41.558501   4.369264           1  
2009    415.886955       12.067620        60.419921   3.669712           1  
2010    526.424171       13.894419        66.687695   4.435821           1  

[2011 rows x 10 columns]

#Split the Dataset

In [5]:
X = df.drop(['Potability'], axis=1)
y = df['Potability']


In [6]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3)

#Feature Scalling

In [7]:
#Importing librarie
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler()  
scaler.fit(X_train)

X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test) 

#Creating KNN Model

#KNN = 3

In [9]:
from sklearn.neighbors import KNeighborsClassifier  

# Definindo o valor de visinhos
classifier = KNeighborsClassifier(n_neighbors=3)  

#Treinando o modelo, com dados de treinamento
classifier.fit(X_train, y_train)  

KNeighborsClassifier(n_neighbors=3)

In [10]:
KNeighborsClassifier(algorithm='auto', metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

KNeighborsClassifier(n_neighbors=3)

In [11]:
y_pred = classifier.predict(X_test) 

In [12]:
# Importing metrics of validation
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Confuse Matrix
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred), "\n")  

# Classification Report
print("Classification Report: \n", classification_report(y_test, y_pred))  


# 
print('Model of the Accuracy: ' , (accuracy_score(y_test, y_pred) *100))

Confusion Matrix: 
[[273  90]
 [149  92]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.65      0.75      0.70       363
           1       0.51      0.38      0.43       241

    accuracy                           0.60       604
   macro avg       0.58      0.57      0.57       604
weighted avg       0.59      0.60      0.59       604

Model of the Accuracy:  60.43046357615894


#KNN = 57

In [13]:


# Definindo o valor de visinhos
classifier = KNeighborsClassifier(n_neighbors=57)  

#Treinando o modelo, com dados de treinamento
classifier.fit(X_train, y_train)  

KNeighborsClassifier(n_neighbors=57)

In [14]:
KNeighborsClassifier(algorithm='auto', metric='hamming',
           n_neighbors=57, p=2,
           weights='uniform')

KNeighborsClassifier(metric='hamming', n_neighbors=57)

In [15]:
y_pred = classifier.predict(X_test) 

In [16]:
# Importing metrics of validation
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Confuse Matrix
print("Confuse Matrix: ")
print(confusion_matrix(y_test, y_pred), "\n")  

# Classification Report
print("Classification Report: \n", classification_report(y_test, y_pred))  


# 
print('Model of the Accuracy: ' , (accuracy_score(y_test, y_pred) *100))

Confuse Matrix: 
[[353  10]
 [207  34]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.63      0.97      0.76       363
           1       0.77      0.14      0.24       241

    accuracy                           0.64       604
   macro avg       0.70      0.56      0.50       604
weighted avg       0.69      0.64      0.55       604

Model of the Accuracy:  64.0728476821192


#KNN = 101

In [17]:


# Definindo o valor de visinhos
classifier = KNeighborsClassifier(n_neighbors=101)  

#Treinando o modelo, com dados de treinamento
classifier.fit(X_train, y_train)  

KNeighborsClassifier(n_neighbors=101)

In [18]:
KNeighborsClassifier(algorithm='auto', metric='euclidian',
            n_neighbors=101, p=2,
           weights='uniform')

KNeighborsClassifier(metric='euclidian', n_neighbors=101)

In [19]:
y_pred = classifier.predict(X_test) 

In [20]:
# Importing metrics of validation
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Confuse Matrix
print("Confuse Matrix: ")
print(confusion_matrix(y_test, y_pred), "\n")  

# Classification Report
print("Classification Report: \n", classification_report(y_test, y_pred))  


# 
print('Model of the Accuracy: ' , (accuracy_score(y_test, y_pred) *100))

Confuse Matrix: 
[[359   4]
 [226  15]] 

Classification Report: 
               precision    recall  f1-score   support

           0       0.61      0.99      0.76       363
           1       0.79      0.06      0.12       241

    accuracy                           0.62       604
   macro avg       0.70      0.53      0.44       604
weighted avg       0.68      0.62      0.50       604

Model of the Accuracy:  61.920529801324506
